### ISSUE TITLE
Passing props other than string

### ISSUE THREAD

**Issue by anbuneeda** [chrisvfritz/hello-vue-components#11]
Hi
I have created webcomponets using target --wc build target command. The component has a prop to accept json object. when i drop the web component in HTML and trying to pass JSON object as the same way if you use this componet in Vue. 

"<"my-element :prop1="{fname:'test'}">"<"/my-element> // the value is not event detected
"<"my-element prop1="{fname:'test'}">"<"/my-element> // throws error prop expect object and not string.

as its a HTML, i am trying to pass a jS variable(JSON) and i couldn't. Other than string value , i am not able to pass any other value.

is document.queryselector('my-element').prop1 is a only way to assign values?

**Comment by chrisvfritz** [comment]
I haven't used the `wc` build target extensively. Perhaps this is a limitation of web components? Either way, it sounds like a potential issue with [Vue CLI](https://github.com/vuejs/vue-cli) rather than this project.
