### ISSUE TITLE
"yarn dev" fails because it wants components to be installed as dependencies

### ISSUE THREAD

**Issue by HerrBertling** [chrisvfritz/hello-vue-components#3]
I know this is currently in alpha, but I still wanted to ask: When running `yarn dev` with a fresh clone of this project, I get the following error:

```
Failed to compile with 3 errors 

These dependencies were not found:

* hello-vue-components in ./demo/main.js
* hello-vue-components.hello-a in ./demo/main.js
* hello-vue-components.hello-b in ./demo/main.js

To install them, you can run: npm install --save hello-vue-components hello-vue-components.hello-a hello-vue-components.hello-b
```

Which I get, I did not do that. Removing these lines (of course) helps, because then I can't even run into this issue: https://github.com/chrisvfritz/hello-vue-components/blob/master/demo/main.js#L4-L10

Am I [holding this wrong](https://www.urbandictionary.com/define.php?term=You%27re%20Holding%20It%20Wrong)? Is this known? What should be done to prevent this?

Thanks for any help – happy to contribute, even though I suspect this is a bit beyond my JS/Vue knowledge 🙈 

EDIT: Reading this again, I think the most important question is missing: Shouldn't this work without the `npm install` initially?

**Comment by chrisvfritz** [comment]
Just fixed this!
