### ISSUE TITLE
[feature] "Moderate" build process?

### ISSUE THREAD

**Issue by HerrBertling** [chrisvfritz/hello-vue-components#7]
As you might notice through the issues I'm opening, I'm doing quite some stuff based on this repo right now :)

I wondered whether you might be up to adding some `console.logs` to the build process – I found it rather opaque to start the process and then not getting any feedback while the packages are being built.

So I threw in some `console.info` lines and carefully crafted fitting emojis (well… :wink:).

![image](https://user-images.githubusercontent.com/1827373/48789933-7723b300-ecee-11e8-882c-52d8077fa240.png)

Since that screenshot had to come from somewhere, here's the diff, so adding this would be rather simple: https://github.com/chrisvfritz/hello-vue-components/compare/master...HerrBertling:feat/add-console-logs-to-build

**Comment by chrisvfritz** [comment]
I like it. 🙂 Just added this!
