### ISSUE TITLE
Add an example with vue-router

### ISSUE THREAD

**Issue by EvanBurbidge** [chrisvfritz/hello-vue-components#8]
First of all awesome work,

I'd like to pick your brains about whether or not it would be easy to setup an example that exports a full vuejs application and not just components. The reason I say this is that all lerna examples seem to just use components as their exports. None of them allow you to install app2 into app1 and have seemless routing between both packages.

Would be quite handy to have at enterprise level apps.

Any ideas on how one would go about that?

**Comment by angeliski** [comment]
I would like to see that too :)

**Comment by EvanBurbidge** [comment]
@angeliski have you done anything in regards to it? I'm still trying to crack it!

**Comment by angeliski** [comment]
Hi @EvanBurbidge I don't tried, but maybe you should not expose the full application. 
You can segregate your packages to export the routes config and use I main entry point like a orchestation .

Or you can use a SPA manager like: https://github.com/CanopyTax/single-spa

**Comment by EvanBurbidge** [comment]
I might give that a shot. Need to keep trying this a little bit first though. Our BE wouldn't be setup to handle that. 

Thanks for the tip @angeliski

**Comment by angeliski** [comment]
@EvanBurbidge Would you be able to make an example repository available for me to take a look at? Maybe I can suggest some other approach.

**Comment by EvanBurbidge** [comment]
@angeliski https://github.com/EvanBurbidge/mono-repo-tester/ there ya go, its simply build app2 as a lib and install into app1, but with lazy loaded routes in app2

**Comment by chrisvfritz** [comment]
Sorry for the delayed reply. I apparently wasn't watching this repo, so never saw notifications about issues/PRs. 😅 I think exporting an application is a different enough use case that it's beyond the scope of this project. However, feel free to keep discussing the problem here. 🙂

**Comment by EvanBurbidge** [comment]
Hey @chrisvfritz  no problem! @angeliski the approach i've ended up taking is to not compile the development applications, instead now I am writing projects and maintaining an internal vue cli plugin which will add all non duplicated peer deps into the "consuming applications". I'm also leveraging Lerna hoisting in order to ensure that my repo doesn't duplicate packages across the board.

**Comment by angeliski** [comment]
Nice @EvanBurbidge ! You can share some code example how do you manager that?
I think will be really awesome see the orchestration working
Cheers

**Comment by EvanBurbidge** [comment]
Yeah I'll write something up tonight as a basic example.
